services:
  # Grid services
  preston.customerPetList.grid.definition.factory.pets:
    class: 'Preston\CustomerPetList\Grid\Definition\Factory\PetGridDefinitionFactory'
    parent: 'prestashop.core.grid.definition.factory.abstract_grid_definition'

  preston.customerPetList.grid.query_builder.pet:
    class: 'Preston\CustomerPetList\Grid\Query\PetQueryBuilder'
    parent: 'prestashop.core.grid.abstract_query_builder'
    public: true
    arguments:
      - '@prestashop.core.query.doctrine_search_criteria_applicator'
      - "@=service('prestashop.adapter.legacy.context').getContext().language.id"
      - "@=service('prestashop.adapter.legacy.context').getContext().shop.id"
      - "@=service('prestashop.adapter.legacy.context').getContext().shop.id_shop_group"
      - "@=service('prestashop.adapter.legacy.context').getContext().shop.getGroup().share_stock"
      - '@prestashop.core.grid.query.filter.doctrine_filter_applicator'
      - '@prestashop.adapter.legacy.configuration'

  preston.customerPetList.grid.data_provider.pets:
    class: '%prestashop.core.grid.data.factory.doctrine_grid_data_factory%'
    arguments:
      - '@preston.customerPetList.grid.query_builder.pet'
      - '@prestashop.core.hook.dispatcher'
      - '@prestashop.core.grid.query.doctrine_query_parser'
      - 'pet'

  preston.customerPetList.grid.factory.pets:
    class: 'PrestaShop\PrestaShop\Core\Grid\GridFactory'
    public: true
    arguments:
      - '@preston.customerPetList.grid.definition.factory.pets'
      - '@preston.customerPetList.grid.data_provider.pets'
      - '@prestashop.core.grid.filter.form_factory'
      - '@prestashop.core.hook.dispatcher'

  preston.customerPetList.form.pet_form_data_provider:
    class: 'Preston\CustomerPetList\Form\PetFormDataProvider'

  preston.customerPetList.form.pet_form_data_handler:
    class: 'Preston\CustomerPetList\Form\PetFormDataHandler'

  preston.customerPetList.form.pet_form_builder:
    class: 'PrestaShop\PrestaShop\Core\Form\IdentifiableObject\Builder\FormBuilder'
    factory: 'prestashop.core.form.builder.form_builder_factory:create'
    arguments:
      - 'Preston\CustomerPetList\Form\PetFormType'
      - '@preston.customerPetList.form.pet_form_data_provider'

  preston.customerPetList.form.pet_form_handler:
    class: 'PrestaShop\PrestaShop\Core\Form\IdentifiableObject\Handler\FormHandler'
    factory: 'prestashop.core.form.identifiable_object.handler.form_handler_factory:create'
    arguments:
      - '@preston.customerPetList.form.pet_form_data_handler'
